config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('', include('my_blog.urls', namespace='my_blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view()  , name='product_list'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/create/', ProductCreateView.as_view(), name="product_create"),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name="product_update"),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name="product_delete"),

]

catalog/models.py
from django.db import models


class Category(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, verbose_name="id")
    category_name = models.CharField(max_length=50, verbose_name="Наименование")
    description = models.TextField(
        max_length=300, verbose_name="Описание", null=True, blank=True
    )

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"


class Product(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, verbose_name="id")
    product_name = models.CharField(
        max_length=50,
        verbose_name="Наименование",
        help_text="Введите наименование продукта",
    )
    description = models.TextField(
        max_length=300, verbose_name="Описание", null=True, blank=True
    )
    image = models.ImageField(
        upload_to="photos", verbose_name="Фотография", null=True, blank=True
    )
    category_name = models.CharField(max_length=50, verbose_name="Категория")
    price = models.IntegerField(verbose_name="Цена")
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания", editable=False, blank=True
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата последнего изменения",
        editable=False,
        blank=True,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="products",
    )

    def __str__(self):
        return f"{self.product_name} {self.category_name}"

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        ordering = [
            "product_name",
        ]

catalog/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'description', 'price', 'image', 'category_name', 'category']

catalog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from catalog.models import Product


class ProductListView(ListView):
    model = Product

class ProductDetailView(DetailView):
    model = Product

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object

class ProductCreateView(CreateView):
    model = Product
    fields = ("product_name", "description", "image", "category_name", "price")
    success_url = reverse_lazy('catalog:product_list')

class ProductUpdateView(UpdateView):
    model = Product
    fields = ("product_name", "description", "image", "category_name", "price")
    success_url = reverse_lazy('catalog:product_list')

    def get_success_url(self):
        return reverse('catalog:product_detail', args=[self.kwargs.get('pk')])

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

templates/catalog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Astro v5.7.10">
    <title>Album example · Bootstrap v5.3</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">
    <script src="{% static 'js/color-modes.js' %}"></script>
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <meta name="theme-color" content="#712cf9">
    <style>
        .bd-placeholder-img{font-size:1.125rem;text-anchor:middle;-webkit-user-select:none;-moz-user-select:none;user-select:none}@media (min-width: 768px){.bd-placeholder-img-lg{font-size:3.5rem}}.b-example-divider{width:100%;height:3rem;background-color:#0000001a;border:solid rgba(0,0,0,.15);border-width:1px 0;box-shadow:inset 0 .5em 1.5em #0000001a,inset 0 .125em .5em #00000026}.b-example-vr{flex-shrink:0;width:1.5rem;height:100vh}.bi{vertical-align:-.125em;fill:currentColor}.nav-scroller{position:relative;z-index:2;height:2.75rem;overflow-y:hidden}.nav-scroller .nav{display:flex;flex-wrap:nowrap;padding-bottom:1rem;margin-top:-1px;overflow-x:auto;text-align:center;white-space:nowrap;-webkit-overflow-scrolling:touch}.btn-bd-primary{--bd-violet-bg: #712cf9;--bd-violet-rgb: 112.520718, 44.062154, 249.437846;--bs-btn-font-weight: 600;--bs-btn-color: var(--bs-white);--bs-btn-bg: var(--bd-violet-bg);--bs-btn-border-color: var(--bd-violet-bg);--bs-btn-hover-color: var(--bs-white);--bs-btn-hover-bg: #6528e0;--bs-btn-hover-border-color: #6528e0;--bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);--bs-btn-active-color: var(--bs-btn-hover-color);--bs-btn-active-bg: #5a23c8;--bs-btn-active-border-color: #5a23c8}.bd-mode-toggle{z-index:1500}.bd-mode-toggle .bi{width:1em;height:1em}.bd-mode-toggle .dropdown-menu .active .bi{display:block!important}
    </style>
</head>
<body>
<symbol id="check2" viewBox="0 0 16 16">
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
</symbol>
<symbol id="circle-half" viewBox="0 0 16 16">
    <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"></path>
</symbol>
<symbol id="moon-stars-fill" viewBox="0 0 16 16">
    <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
    <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path>
</symbol>
<symbol id="sun-fill" viewBox="0 0 16 16">
    <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"></path>
</symbol>
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button"
            aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)">
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span></button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
            </button>
        </li>
    </ul>
</div>
<header data-bs-theme="dark">
    {% include 'catalog/mails/mail_menu.html' %}
</header>
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Первый продуктовый интернет маркет</h1>
                <p class="lead text-body-secondary">Продуктовая ярмарка</p>
                <a href="{% url 'catalog:product_create' %}">
                <input class="btn btn-primary" type="button" value="Добавить продукт"></a>
            </div>
        </div>
    </section>

    {% block content%}
    {% endblock %}
</main>
<footer class="text-body-secondary py-5">
    <div class="container">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
        <p class="fs-4 mb-3">Интернет маркет вкусных продуктов</p>
        <p class="mb-0">Устали стоять в очередях и носить тяжелые пакеты? Забудьте об этих неудобствах! В нашем интернет-магазине Вы
            можете купить онлайн все необходимые продукты с доставкой на дом. Удобный каталог и система поиска позволят
            Вам всё быстро найти и оформить заказ в любое удобное для Вас время. Просто выберите нужный день и интервал
            доставки, за 15 минут до вручения заказа наш курьер обязательно Вам позвонит. Первый заказ доставим
            бесплатно. Наши цены оправданы и разумны. Хотите покупать выгоднее? Участвуйте в акциях, бонусных
            программах и тест-драйвах!

            Деликатеска предоставляет покупателям гарантии возврата в случае возникновения претензий по качеству. Просто
            сообщите нам о проблеме по круглосуточному телефону +7 495 500-9-500 .

            Первоклассный сервис, удобная доставка, свежесть и супергарантия: мы делаем все, чтобы Ваша жизнь была
            комфортнее и вкуснее.</p>
    </div>
</footer>
<script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/catalog/contacts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Домашнее задание - Bootstrap</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h3 class="text-bg-info p-3 text-center mt-5">Контакты</h3>
        <form method="post" action="">
            {% csrf_token %}
            <div class="row">
                <div class="col-2"></div>
                <div class="col-8">
                    <div class="row mt-5">
                        <div class="col-5">
                            <div class="card bg-body text-body p-3">
                                <form>
                                    <div class="mb-3">
                                        <input type="text" id="name" name="name" class="form-control" placeholder="Алиса">
                                    </div>
                                    <div class="mb-3">
                                        <div class="input-group">
                                            <span class="input-group-text">@</span>
                                            <input type="text" class="form-control" placeholder="examle@examle">
                                        </div>
                                        <div class="mb-3 mt-3">
                                            <textarea class="form-control" id="message" rows="3" name="message" required placeholder="Сообщение"></textarea>
                                        </div>
                                        <button type="submit" class="btn btn-info w-100">Отправить</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="col-1"></div>
                        <div class="col-6 mt-3">
                                <div class="card-body">
                                    <h5>Наши контакты</h5>
                                    <div class="row mt-3">
                                        <p class="lh-1">На странице контактов вы найдёте адрес, телефон и график работы магазина. Вы также можете воспользоваться картой, чтобы найти ближайший магазин Hoff.
                                        <p class="lh-sm">Если у вас возникли вопросы или нужна помощь, не стесняйтесь обращаться в службу поддержки Hoff. Специалисты службы поддержки помогут вам решить любой вопрос и сделать ваш шопинг в Hoff максимально комфортным.
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
                <div class="col-2"></div>
            </div>
        </form>
    </div>
    <script src="/static/js/bootstar.bundle.min.js"></script>
</body>
</html>

templates/catalog/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Домашнее задание - Bootstrap</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="text-bg-primary p-3 text-center mt-5">Главная</h1>
        <h5 class="text-bg-info p-3 text-center">Вы находитесь на сайте, предназначенном для продажи товаров.</h5>
        <div class="row">
            <div class="col-1"></div>
            <div class="col-10">
                <div class="row">
                    <div class="col-4">
                        <div class="card text-center mt-3">
                            <div class="card-header">
                                Товар 1
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">$ 100</h5>
                                <p class="card-text">10 users included, 2 GB of storage, Email support, Help center access.</p>
                                <a href="#" class="btn btn-outline-primary w-100">Купить</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="card text-center mt-3">
                            <div class="card-header">
                                Товар 1
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">$ 100</h5>
                                <p class="card-text">10 users included, 2 GB of storage, Email support, Help center access.</p>
                                <a href="#" class="btn btn-outline-primary w-100">Купить</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="card text-center mt-3">
                            <div class="card-header">
                                Товар 1
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">$ 100</h5>
                                <p class="card-text">10 users included, 2 GB of storage, Email support, Help center access.</p>
                                <a href="#" class="btn btn-outline-primary w-100">Купить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-1"></div>
        </div>
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/catalog/product_confirm_delete.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card shadow-sm">
                    <p class="card-text">Действительно хотите удалить{{ object.product_name }}</p>
                    <div class="card-body">
                        {% csrf_token %}
                        <div class="d-grid mt-3">
                            <button type="submit" class="btn btn-outline-primary">Удалить</button>
                            <a class="btn btn-primary" href="{% url 'catalog:product_list' %}">Отменить</a>
                        </div>

                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content%}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ product.image | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">{{ object.product_name}}</p>
                        <p class="card-text">Описание: {{object.description | truncatechars:100 }}</p>
                        <p class="card-text">Категория: {{object.category_name }}</p>
                        <p class="card-text">Цена: {{object.price}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'catalog:product_list' %}" role="button">Назад</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/catalog/product_form.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="container mt-5">
    <form method="post" enctype="multipart/form-data">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow-sm">
                    {% if object %}
                    <p class="card-text">Редактирование продукта</p>
                    {% else %}
                    <p class="card-text">Создание продукта</p>
                    {% endif %}
                    <div class="card-body">
                        <h2 class="card-title text-center mb-4">Добавить товар</h2>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-grid mt-3">
                            <button type="submit" class="btn btn-outline-primary">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for product in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ product.image | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">{{ product.product_name }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'catalog:product_detail' product.pk %}"
                                   role="button">Инфо</a>
                                 <a class="btn btn-primary" href="{% url 'catalog:product_update' product.pk %}"
                                   role="button">Редактировать</a>
                                 <a class="btn btn-primary" href="{% url 'catalog:product_delete' product.pk %}"
                                   role="button">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}